name: Generate Items

on:
  push:
    branches:
      - main
  schedule:
    # Every day at 6:00 AM UTC
    - cron: "0 6 * * *"

jobs:
  run-deno-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Deno task
        run: deno task generate-items

      - name: ll
        run: ls -lsa

