name: Generate Items

on:
  push:
    branches:
      - main
  schedule:
    # Every day at 6:00 AM UTC
    - cron: "0 6 * * *"

jobs:
  run-deno-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Deploy to Cloudflare
        env:
          PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: deno task generate-items

      - name: ll
        run: ls -lsa
      
      - name: Create dist directory
        run: mkdir ./dist
      
      - name: Copy files
        run: cp ./items.json ./src/ui/random-tiny.html ./dist

      - name: Install Cloudflare Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare Pages
        run: wrangler pages deploy ./dist --project-name ${{ secrets.CLOUDFLARE_PROJECT_NAME }} --branch main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
